# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: E2E TESTING

on:
  push:
   branches: 
    -master
  pull_request:
   branches: 
    -master
  schedule:
    - cron: '00 21 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write

steps:
      # 2. عمل Checkout للكود بتاعك
      - name: Checkout code
        uses: actions/checkout@v4

      # 3. إعداد البيئة (مثال: لو شغال Java و Maven)
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: setup maven
       uses: stCarolas/setup-maven@v5
       with:
         maven-version 3.9.14
      - name: Running Tests
       run: mvn clean test
      - name: upload test-results
        uses: actions/upload-artifact@v7
        with:
           name: chrome-Windows Reports
           path: "test-output/reports/*.html"


    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
