name: Saucedemo QA Automation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # الزرار السحري للرن المانيوال

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # تحديث للإصدار الرابع

    - name: Set up JDK 21
      uses: actions/setup-java@v4 # تحديث للإصدار الرابع
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Run Tests with Maven
      run: mvn clean test
      continue-on-error: true # عشان لو تست فشل، الـ Workflow يكمل ويرفع التقرير برضو

    - name: Upload Allure Results
      if: always()
      uses: actions/upload-artifact@v4 # أحدث إصدار لرفع الملفات
      with:
        name: allure-results-artifact
        path: target/allure-results # المسار الافتراضي لـ ميفن عشان يلقط الملفات صح